"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
command_timeout = 2000

format = """
$os\
$username\
$directory\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
$git_state\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$dotnet\
$package\
$docker_context\
$kubernetes\
$shell\
$container\
$jobs\
$memory_usage\
$time\
$cmd_duration\
$status\
$line_break\
$character\
"""

# Using default palette for Windows terminal compatibility
palette = 'default'

[palettes.default]
color_ok = 'bright-green'
color_danger = 'bright-red'
color_caution = 'bright-yellow'
color_os = 'red'
color_username = 'red'
color_directory = 'yellow'
color_git = 'cyan'
color_git_added = 'bright-green'
color_git_deleted = 'bright-red'
color_env = 'blue'
color_kubernetes = 'purple'
color_docker = 'blue'
color_shell = ''
color_container = ''
color_other = ''
color_time = ''
color_duration = ''
color_vimcmd_ok = 'green'
color_vimcmd_replace = 'purple'
color_vimcmd_visual = 'yellow'

[os]
disabled = false
style = "fg:color_os"
format = '[$symbol]($style)'

[os.symbols]
Windows = "Û∞ç≤"

[username]
show_always = true
style_user = "fg:color_username"
style_root = "bold fg:color_danger"
format = '[ $user ]($style)'

[directory]
style = "fg:color_directory"
read_only_style = "fg:color_directory"
repo_root_style = "bold fg:color_directory"
format = "[ $path ]($style)"
read_only = " "
home_symbol = "~"
truncation_symbol = "‚Ä¶/"
truncation_length = 3
truncate_to_repo = true
use_logical_path = true

[git_branch]
symbol = "Û∞ò¨ "
style = "fg:color_git"
format = '( [$symbol $branch]($style) )'
only_attached = true
truncation_length = 25
truncation_symbol = "..."
disabled = false

[git_commit]
style = "fg:color_git"
format = "( [($tag)(@$hash)]($style) )"
commit_hash_length = 7
only_detached = true
tag_symbol = " "
tag_disabled = false
disabled = false

[git_status]
style = "fg:color_git"
format = '([$ahead_behind]($style) )([$all_status]($style) )'
stashed = "*${count}"
ahead = "‚á°${count}"
behind = "‚á£${count}"
up_to_date = ""
diverged = "‚á°${ahead_count}‚á£${behind_count}"
conflicted = "=${count}"
deleted = "√ó${count}"
renamed = "¬ª${count}"
modified = "!${count}"
staged = "+${count}"
untracked = "?${count}"
disabled = false

[git_metrics]
format = '([([+$added]($added_style))([-$deleted]($deleted_style))](fg:color_git) )'
added_style = "fg:color_git_added"
deleted_style = "fg:color_git_deleted"
only_nonzero_diffs = true
disabled = false

[git_state]
style = "fg:color_danger"
format = '([$state( $progress_current/$progress_total)]($style bold) )'
rebase = "REBASING"
merge = "MERGING"
revert = "REVERTING"
cherry_pick = "CHERRY-PICKING"
bisect = "BISECTING"
am = "AM"
am_or_rebase = "AM/REBASE"
disabled = false

[nodejs]
symbol = "Û∞éô "
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[c]
symbol = ""
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[rust]
symbol = "Rs"
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[golang]
symbol = "Go"
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[php]
symbol = "üêò"
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[java]
symbol = "‚òï"
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[kotlin]
symbol = ""
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[haskell]
symbol = ""
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[python]
symbol = "Û∞å† "
style = "fg:color_env"
format = '( [$symbol( $version)( $virtualenv)]($style) )'
version_format = '${raw}'

[dotnet]
symbol = ""
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[package]
disabled = false
symbol = "üì¶"
style = "fg:color_env"
format = '( [$symbol( $version)]($style) )'

[docker_context]
symbol = "üê≥"
style = "fg:color_docker"
format = '( [$symbol( $context)]($style) )'

[kubernetes]
symbol = "‚ò∏"
style = "fg:color_kubernetes"
format = '( [($symbol( $cluster))]($style) )'
disabled = false

[shell]
disabled = false
format = '[  $indicator ]($style)'
powershell_indicator = "pwsh"
pwsh_indicator = "pwsh"
cmd_indicator = "cmd"
style = "fg:color_shell"

[container]
style = "fg:color_container"
format = '( [$symbol $name]($style) )'

[jobs]
symbol = ""
style = "fg:color_other"
format = '( [$symbol( $number)]($style) )'
symbol_threshold = 1
number_threshold = 1

[memory_usage]
threshold = 75
symbol = ""
style = "fg:color_other"
format = '( [$symbol( ${ram})]($style) )'
disabled = true

[time]
disabled = true
time_format = "%R"
style = "fg:color_time"
format = '( [ $time]($style) )'

[cmd_duration]
min_time = 2000
format = '( [ $duration]($style) )'
style = 'fg:color_duration'
show_milliseconds = false
disabled = false

[status]
disabled = false
format = '( [$symbol( $common_meaning)( $signal_name)]($style) )'
map_symbol = true
pipestatus = true
symbol = '‚úñ'
success_symbol = ''
not_executable_symbol = ''
not_found_symbol = ''
sigint_symbol = ''
signal_symbol = ''
style = 'bold fg:color_danger'
recognize_signal_code = true

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[‚ùØ](bold fg:color_ok)'
error_symbol = '[‚ùØ](bold fg:color_danger)'
vimcmd_symbol = '[‚ùÆ](bold fg:color_vimcmd_ok)'
vimcmd_replace_one_symbol = '[‚ùÆ](bold fg:color_vimcmd_replace)'
vimcmd_replace_symbol = '[‚ùÆ](bold fg:color_vimcmd_replace)'
vimcmd_visual_symbol = '[‚ùÆ](bold fg:color_vimcmd_visual)'
